<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8pxwZLH\testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8pxwZLH/testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer.php') {
    touch(__DIR__.'/Container8pxwZLH.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer::class, false)) {
    \class_alias(\Container8pxwZLH\testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer::class, testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer::class, false);
}

return new \Container8pxwZLH\testsSymfony_Component_HttpKernel_Kernel4zHK2aRDevDebugContainer([
    'container.build_hash' => '8pxwZLH',
    'container.build_id' => '27a7140b',
    'container.build_time' => 1574344514,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8pxwZLH');
