<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE46D6wx\testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE46D6wx/testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE46D6wx.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer::class, false)) {
    \class_alias(\ContainerE46D6wx\testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer::class, testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer::class, false);
}

return new \ContainerE46D6wx\testsSymfony_Component_HttpKernel_KernelzMxZCWaDevDebugContainer([
    'container.build_hash' => 'E46D6wx',
    'container.build_id' => 'f06022e2',
    'container.build_time' => 1574344378,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE46D6wx');
