<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCoQmmm5\testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCoQmmm5/testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCoQmmm5.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer::class, false)) {
    \class_alias(\ContainerCoQmmm5\testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer::class, testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer::class, false);
}

return new \ContainerCoQmmm5\testsSymfony_Component_HttpKernel_Kernel7bnZwXuDevDebugContainer([
    'container.build_hash' => 'CoQmmm5',
    'container.build_id' => 'cba241ed',
    'container.build_time' => 1574344320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCoQmmm5');
