<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNcfs0RZ\testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNcfs0RZ/testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNcfs0RZ.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer::class, false)) {
    \class_alias(\ContainerNcfs0RZ\testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer::class, testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer::class, false);
}

return new \ContainerNcfs0RZ\testsSymfony_Component_HttpKernel_Kernel4CPc_YVDevDebugContainer([
    'container.build_hash' => 'Ncfs0RZ',
    'container.build_id' => '48a77b19',
    'container.build_time' => 1574344525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNcfs0RZ');
