<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQkFcKRr\testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQkFcKRr/testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQkFcKRr.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer::class, false)) {
    \class_alias(\ContainerQkFcKRr\testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer::class, testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer::class, false);
}

return new \ContainerQkFcKRr\testsSymfony_Component_HttpKernel_KernelbDtvOYTDevDebugContainer([
    'container.build_hash' => 'QkFcKRr',
    'container.build_id' => '53e66a7c',
    'container.build_time' => 1574344391,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQkFcKRr');
