<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRyfQ7AK\testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRyfQ7AK/testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRyfQ7AK.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer::class, false)) {
    \class_alias(\ContainerRyfQ7AK\testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer::class, testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer::class, false);
}

return new \ContainerRyfQ7AK\testsSymfony_Component_HttpKernel_KernelA0bpEloDevDebugContainer([
    'container.build_hash' => 'RyfQ7AK',
    'container.build_id' => '1ea61451',
    'container.build_time' => 1574344091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRyfQ7AK');
