<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPlKzcUh\testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPlKzcUh/testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPlKzcUh.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer::class, false)) {
    \class_alias(\ContainerPlKzcUh\testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer::class, testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer::class, false);
}

return new \ContainerPlKzcUh\testsSymfony_Component_HttpKernel_Kernel_vAnEXHDevDebugContainer([
    'container.build_hash' => 'PlKzcUh',
    'container.build_id' => '62bd0ff4',
    'container.build_time' => 1574344360,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPlKzcUh');
