<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR3xkndm\testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR3xkndm/testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR3xkndm.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer::class, false)) {
    \class_alias(\ContainerR3xkndm\testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer::class, testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer::class, false);
}

return new \ContainerR3xkndm\testsSymfony_Component_HttpKernel_KernelqCmGEzMDevDebugContainer([
    'container.build_hash' => 'R3xkndm',
    'container.build_id' => '419d0c65',
    'container.build_time' => 1574344272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR3xkndm');
