<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVF4SZjX\testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVF4SZjX/testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVF4SZjX.legacy');

    return;
}

if (!\class_exists(testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer::class, false)) {
    \class_alias(\ContainerVF4SZjX\testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer::class, testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer::class, false);
}

return new \ContainerVF4SZjX\testsSymfony_Component_HttpKernel_Kernel9NZqi9CDevDebugContainer([
    'container.build_hash' => 'VF4SZjX',
    'container.build_id' => 'd264f762',
    'container.build_time' => 1574344303,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVF4SZjX');
