name: Lint

on:
    push:
        branches: [ main ]
    pull_request: null
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "${{ matrix.check.name }} (PHP ${{ matrix.php }})"
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.2' ]
                check:
                    -   name: PHPStan
                        command: make phpstan

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: composer
                    coverage: none

            -   name: Run ${{ matrix.check.name }}
                run: ${{ matrix.check.command }}
