name: Lint

on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Lint ${{ matrix.check.name }}
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
                check:
                    -   name: PHPStan
                        command: make phpstan

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    tools: composer
                    coverage: none

            -   name: Run ${{ matrix.check.name }}
                run: ${{ matrix.check.command }}
