name: "Tests"

on:
    push:
        branches: ["main"]
    pull_request: null
    schedule:
        # Do not make it the first of the month and/or midnight since it is a very busy time
        - cron: "* 10 5 * *"

jobs:
    tests:
        runs-on: "ubuntu-latest"
        name: "Tests (PHP ${{ matrix.php }})"
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.3"
                    - "8.4"

        steps:
            -   name: "Check out repository code"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: "Install Composer dependencies"
                uses: "ramsey/composer-install@v3"

            -   name: "Run tests"
                run: "make phpunit"

    symfony-version:
        runs-on: "ubuntu-latest"
        name: "Tests (PHP ${{ matrix.php }}) with Symfony ${{ matrix.symfony.version_name }} (deps: ${{ matrix.dependency-versions }})"
        strategy:
            fail-fast: false
            matrix:
                dependency-versions:
                    - "lowest"
                    - "highest"
                php:
                    - "8.3"
                    - "8.4"
                symfony:
                    - version_name: "6.4"
                      conflict: "<6.4 || >=7.0"
                    - version_name: "7.2"
                      conflict: "<7.2 || >=8.0"

        steps:
            -   name: "Check out repository code"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    tools: "composer"

            -   name: "Fix the Symfony versions"
                run: "bin/fix-symfony-versions \"${{ matrix.symfony.conflict }}\""

            -   name: "Install Composer dependencies"
                uses: "ramsey/composer-install@v3"
                with:
                    dependency-versions: "${{ matrix.dependency-versions }}"

            -   name: "Run tests"
                run: "make phpunit"

    infection:
        runs-on: "ubuntu-latest"
        name: "Infection (PHP ${{ matrix.php }})"
        strategy:
            fail-fast: false
            matrix:
                php:
                    - "8.3"

        steps:
            -   name: "Check out repository code"
                uses: "actions/checkout@v4"

            -   name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
                    tools: "composer"
                    coverage: "pcov"

            -   name: "Install Composer dependencies"
                uses: "ramsey/composer-install@v3"

            -   name: "Run tests with coverage and Infection"
                run: "make infection"

    # This is a "trick", a meta task which does not change, and we can use in
    # the protected branch rules as opposed to the individual tests which
    # may change regularly.
    validate-tests:
        name: "Tests Status"
        runs-on: "ubuntu-latest"
        needs:
            - "tests"
            - "symfony-version"
            - "infection"
        if: "always()"
        steps:
            - name: "Successful run"
              if: "${{ !(contains(needs.*.result, 'failure')) }}"
              run: "exit 0"

            - name: "Failing run"
              if: "${{ contains(needs.*.result, 'failure') }}"
              run: "exit 1"
